"""Update user primary key to email_or_mobile and link feedback directly

Revision ID: fbb9abf812b5
Revises: d18d7686dfbf
Create Date: 2025-10-19 19:24:37.298195

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = 'fbb9abf812b5'
down_revision = 'd18d7686dfbf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # This migration was generated against an earlier schema and may be applied
    # to DBs that don't have all intermediate columns. Make operations idempotent.
    bind = op.get_bind()
    insp = inspect(bind)

    feedback_cols = {c["name"] for c in insp.get_columns("feedback")}
    users_cols = {c["name"] for c in insp.get_columns("users")}

    if "email_or_mobile" in feedback_cols:
        op.drop_column("feedback", "email_or_mobile")
    if "user_ref" in feedback_cols:
        op.drop_column("feedback", "user_ref")

    if "user_email_or_mobile" not in feedback_cols:
        op.add_column("feedback", sa.Column("user_email_or_mobile", sa.String(length=100), nullable=True))

    # Create FK only if not already present
    fks = {fk["name"] for fk in insp.get_foreign_keys("feedback")}
    if "feedback_user_email_or_mobile_fkey" not in fks:
        op.create_foreign_key(
            "feedback_user_email_or_mobile_fkey",
            "feedback",
            "users",
            ["user_email_or_mobile"],
            ["email_or_mobile"],
        )

    # Switch users PK to email_or_mobile only if id exists (old schema)
    if "id" in users_cols and "email_or_mobile" in users_cols:
        op.drop_constraint("users_pkey", "users", type_="primary")
        op.drop_column("users", "id")
        op.create_primary_key("users_pkey", "users", ["email_or_mobile"])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email_or_mobile', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email_or_mobile'), 'users', ['email_or_mobile'], unique=True)
    op.create_table('feedback',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('channel', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sentiment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('topics', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email_or_mobile', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('sentiment_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('feedback_company_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('feedback_pkey'))
    )
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=False)
    op.create_index(op.f('ix_feedback_company_id'), 'feedback', ['company_id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('companies_pkey'))
    )
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_email'), 'companies', ['email'], unique=True)
    # ### end Alembic commands ###
