from fastapi import APIRouter, Depends, HTTPException, UploadFile, File
from sqlalchemy.orm import Session
from backend.app.db.session import get_db
from backend.app.modules.feedback.schema import FeedbackCreate, FeedbackRead, FeedbackBulkCreate
from backend.app.modules.feedback.service import get_feedbacks, create_feedback, create_feedbacks_bulk
from backend.app.core.security import get_current_company
import pandas as pd
import os
from googleapiclient.discovery import build
from google.oauth2.credentials import Credentials
import imaplib
import email
from backend.app.modules.products.model import Product

router = APIRouter(prefix="/feedback", tags=["feedback"])


@router.get("/", response_model=list[FeedbackRead])
def read_feedbacks(db: Session = Depends(get_db), current_company=Depends(get_current_company)):
    feedbacks = get_feedbacks(db, current_company.id)
    return feedbacks


@router.post("/bulk")
def add_feedback_bulk(feedbacks: list[FeedbackCreate], db: Session = Depends(get_db), current_company=Depends(get_current_company)):
    for fb in feedbacks:
        fb.company_id = current_company.id
    created_feedbacks = create_feedbacks_bulk(db, feedbacks)
    return {"inserted": len(created_feedbacks)}


@router.post("/upload_csv")
async def upload_csv(file: UploadFile = File(...), db: Session = Depends(get_db), current_company=Depends(get_current_company)):
    """
    Upload feedback via CSV.
    
    Required CSV columns:
      - channel: source channel (e.g., email, twitter, google_forms)
      - text: feedback text content
      
    Required (at least one per row):
      - email: customer email address
      - mobile: customer mobile/phone number
      
    Optional CSV columns:
      - name: customer name
      - product_model_number: product model number (must exist in company's products)
      
    Auto-generated by backend (do NOT include in CSV):
      - sentiment: positive / negative / neutral (via TextBlob NLP)
      - sentiment_score: polarity score from -1.0 to +1.0
      - topics: extracted keywords and noun phrases
      - user_id: matched or created based on email/mobile
    """
    df = pd.read_csv(file.file)
    
    # Required columns
    required_cols = ['channel', 'text']
    if not set(required_cols).issubset(df.columns):
        raise HTTPException(
            status_code=400, 
            detail=f"CSV must contain required columns: {', '.join(required_cols)}. "
                   f"Optional: name, product_model_number. "
                   f"At least one of email or mobile must be present per row."
        )
    if df.empty:
        raise HTTPException(status_code=400, detail="CSV file is empty")

    # At least one of email/mobile must exist per row.
    if "email" not in df.columns and "mobile" not in df.columns:
        raise HTTPException(
            status_code=400, 
            detail="CSV must contain at least one of: email, mobile"
        )

    feedbacks = []
    rejected = 0
    for _, row in df.iterrows():
        email_val = str(row['email']).strip() if 'email' in df.columns and pd.notna(row['email']) else None
        mobile_val = str(row['mobile']).strip() if 'mobile' in df.columns and pd.notna(row['mobile']) else None
        if not email_val and not mobile_val:
            rejected += 1
            continue

        product_model_number = str(row['product_model_number']).strip() if 'product_model_number' in df.columns and pd.notna(row['product_model_number']) else None
        if product_model_number:
            product = db.query(Product).filter(
                Product.company_id == current_company.id,
                Product.model_number == product_model_number
            ).first()
            if not product:
                raise HTTPException(status_code=400, detail=f"Invalid product_model_number: {product_model_number}")

        feedback = FeedbackCreate(
            company_id=current_company.id,
            channel=str(row['channel']),
            text=str(row['text']),
            name=str(row['name']).strip() if 'name' in df.columns and pd.notna(row['name']) else None,
            email=email_val,
            mobile=mobile_val,
            product_model_number=product_model_number,
        )
        feedbacks.append(feedback)
    inserted = create_feedbacks_bulk(db, feedbacks)
    return {
        "inserted": len(inserted), 
        "rejected_missing_email_and_mobile": rejected,
        "message": "Sentiment, topics, and sentiment_score were auto-generated by the NLP model."
    }


@router.post("/import_google_forms")
def import_google_forms(sheet_id: str, db: Session = Depends(get_db), current_company=Depends(get_current_company)):
    creds = Credentials.from_authorized_user_file('token.json', ['https://www.googleapis.com/auth/spreadsheets.readonly'])
    service = build('sheets', 'v4', credentials=creds)
    result = service.spreadsheets().values().get(spreadsheetId=sheet_id, range='A1:D').execute()
    values = result.get('values', [])
    feedbacks = []
    for row in values[1:]:
        name = row[0] if len(row) > 0 else "Anonymous"
        text = row[1] if len(row) > 1 else ""
        email_or_mobile = row[2] if len(row) > 2 else "unknown@google.com"
        feedback = FeedbackCreate(
            company_id=current_company.id,
            channel='google_forms',
            text=text,
            name=name,
            product_model_number=None,
        )
        feedbacks.append(feedback)
    inserted = create_feedbacks_bulk(db, feedbacks)
    return {"inserted": len(inserted)}


@router.post("/import_emails")
def import_emails(db: Session = Depends(get_db), current_company=Depends(get_current_company)):
    mail = imaplib.IMAP4_SSL('imap.gmail.com')
    mail.login(os.getenv('GMAIL_USER'), os.getenv('GMAIL_PASS'))
    mail.select('inbox')
    status, messages = mail.search(None, 'UNSEEN')
    messages = messages[0].split()
    feedbacks = []
    for msg_id in messages:
        status, msg_data = mail.fetch(msg_id, '(RFC822)')
        msg = email.message_from_bytes(msg_data[0][1])
        subject = msg['subject']
        body = ""
        if msg.is_multipart():
            for part in msg.walk():
                if part.get_content_type() == "text/plain":
                    body = part.get_payload(decode=True).decode()
                    break
        else:
            body = msg.get_payload(decode=True).decode()
        sender = msg['from']
        name = subject if subject else "Email User"
        email_or_mobile = sender if sender else "unknown@email.com"
        feedback = FeedbackCreate(
            company_id=current_company.id,
            channel='email',
            text=f"{subject}: {body}",
            name=name,
            product_model_number=None,
        )
        feedbacks.append(feedback)
    inserted = create_feedbacks_bulk(db, feedbacks)
    return {"inserted": len(inserted)}


@router.post("/import_twitter")
def import_twitter(
    handle: str,
    db: Session = Depends(get_db),
    current_company=Depends(get_current_company)
):
    return {"error": "Twitter import disabled (snscrape incompatible with Python 3.13)"}

