from sqlalchemy.orm import Session
from sqlalchemy import text
from backend.app.modules.products.model import Product
from backend.app.modules.products.schema import ProductCreate


def get_products_by_company(db: Session, company_id: int):
    return db.query(Product).filter(Product.company_id == company_id).all()


def create_product(db: Session, product: ProductCreate, company_id: int):
    payload = product.model_dump()
    db_product = Product(**payload, company_id=company_id)
    # Non-PK id is generated by DB sequence in this schema; set it explicitly for ORM insert.
    if db_product.id is None:
        db_product.id = db.execute(text("SELECT nextval('products_api_id_seq')")).scalar()
    db.add(db_product)
    db.commit()
    db.refresh(db_product)
    return db_product


def get_product_by_company_and_model(db: Session, company_id: int, model_number: str):
    return db.query(Product).filter(
        Product.company_id == company_id,
        Product.model_number == model_number
    ).first()


def get_product_by_company_and_id(db: Session, company_id: int, product_id: int):
    return db.query(Product).filter(
        Product.company_id == company_id,
        Product.id == product_id
    ).first()

